name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        run: mvn clean install
      - name: Get the version 
        id: get_version 
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/projet-oe.zip
            target/projet-oe-v0.0.1.jar
          automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
          title: Oe ${{ steps.get_version.outputs.VERSION }}
